### ISSUE TITLE
"An exception occurred during message parsing!"

### ISSUE THREAD

**Issue by r00ster91** [meew0/discordcr#109]
I got this as an error in the console. And it says I should report it.

The things I censored here are just the ID and the GUILD_ID. I replaced this with "censored"
I hope its still useful

```C
E, [2018-01-09 09:05:52 +01:00 #168] ERROR -- discordcr: An exception occurred during message parsing! Please report this.
Missing json attribute: username at 1:1
(pertaining to previous exception) Raised with packet:
{"t":"GUILD_BAN_ADD","s":5,"op":0,"d":{"user":{"username":"dorit","id":"censored","discriminator":"3413","bot":true,"avatar":null},"guild_id":"censored"}}
```

Im very sure this happened while `client.create_message` or `client.create_guild_ban`
But I could still see the message and he got banned successfully.

**Comment by z64** [comment]
This is a known issue. It will be fixed by https://github.com/meew0/discordcr/pull/97

**Comment by r00ster91** [comment]
Ah okay!
