### ISSUE TITLE
Exception during parsing all messages from Penguin.bot on all servers

### ISSUE THREAD

**Issue by BlobCodes** [meew0/discordcr#150]
`Missing JSON attribute: mention_roles
  parsing Discord::Gateway::MessageUpdatePayload at 1:1 (JSON::MappingError)
  from lib/discordcr/src/discordcr/mappings/gateway.cr:0:7 in 'initialize'
  from lib/discordcr/src/discordcr/mappings/gateway.cr:302:7 in 'new'
  from /usr/lib/crystal/json/from_json.cr:13:3 in 'from_json'
  from lib/discordcr/src/discordcr/client.cr:550:19 in 'handle_dispatch'
  from lib/discordcr/src/discordcr/client.cr:195:13 in '->'
  from /usr/lib/crystal/fiber.cr:255:3 in 'run'
  from /usr/lib/crystal/fiber.cr:29:34 in '->'
  from ???

(pertaining to previous exception) Raised with packet:
Discord::WebSocket::Packet(@opcode=0_i64 @sequence=266_i64 @data="{\"id\":\"466213529544949765\",\"embeds\":[{\"url\":\"https://api.penguin.bot/uploads/cf5b6d46d0cdc253b2adbbbbdc8ea394bc82f2fcaf62f5e18a8fcfa0c6c5f42e.gif\",\"type\":\"rich\",\"image\":{\"width\":262,\"url\":\"https://api.penguin.bot/uploads/cf5b6d46d0cdc253b2adbbbbdc8ea394bc82f2fcaf62f5e18a8fcfa0c6c5f42e.gif\",\"proxy_url\":\"https://images-ext-2.discordapp.net/external/oQ6qV-db7ZysEqVOPFXmShu6_Nh5_g_W_maJoRAsRc4/https/api.penguin.bot/uploads/cf5b6d46d0cdc253b2adbbbbdc8ea394bc82f2fcaf62f5e18a8fcfa0c6c5f42e.gif\",\"height\":264},\"footer\":{\"text\":\"BlobCodes @ 2:07 PM - 7/10/2018\",\"proxy_icon_url\":\"https://images-ext-2.discordapp.net/external/PBDXGfw-puAgmf3B0Ib2tAlchwEPugAlm0XsFg9E3L0/%3Fsize%3D256/https/cdn.discordapp.com/avatars/96967924798992384/fbe3b94ae3db0e099890075f9dbe2cab.png\",\"icon_url\":\"https://cdn.discordapp.com/avatars/96967924798992384/fbe3b94ae3db0e099890075f9dbe2cab.png?size=256\"},\"color\":2718207}],\"channel_id\":\"362994634349215754\",\"guild_id\":\"362992013366394880\"}" @event_type="MESSAGE_UPDATE")
E, [2018-07-10 14:09:16 +02:00 #2196] ERROR -- discordcr: [Client] An exception occurred during message parsing! Please report this.
Missing JSON attribute: mention_roles
  parsing Discord::Gateway::MessageUpdatePayload at 1:1 (JSON::MappingError)
  from lib/discordcr/src/discordcr/mappings/gateway.cr:0:7 in 'initialize'
  from lib/discordcr/src/discordcr/mappings/gateway.cr:302:7 in 'new'
  from /usr/lib/crystal/json/from_json.cr:13:3 in 'from_json'
  from lib/discordcr/src/discordcr/client.cr:550:19 in 'handle_dispatch'
  from lib/discordcr/src/discordcr/client.cr:195:13 in '->'
  from /usr/lib/crystal/fiber.cr:255:3 in 'run'
  from /usr/lib/crystal/fiber.cr:29:34 in '->'
  from ???

(pertaining to previous exception) Raised with packet:
Discord::WebSocket::Packet(@opcode=0_i64 @sequence=275_i64 @data="{\"id\":\"466214321416962058\",\"embeds\":[{\"type\":\"rich\",\"description\":\"<:_:430096348348547072> <@!96967924798992384>: Your balance is `1,000` gold.\\n\\n[Click here](https://discordbots.org/bot/pbot/vote) and upvote for `500` free gold every 24h.\",\"color\":15844367}],\"channel_id\":\"362994634349215754\",\"guild_id\":\"362992013366394880\"}" @event_type="MESSAGE_UPDATE")`

**Comment by z64** [comment]
This is a known issue and was fixed in #142
