### ISSUE TITLE
Stuff for parsing mentions

### ISSUE THREAD

**Issue by RX14** [meew0/discordcr#35]
proposed interface:

``` cr
parse_mentions(str) do |content|
  case content
  when Discordcr::Mention
    # Mention
  when String
    # message hunk
  end
end
```

Might want a few fancier wrappers around it if required.

**Comment by meew0** [comment]
Why not something simple like

```cr
mentions = Discord.parse_mentions(str)
p mentions # [66237334693085184, 95658408207724544]
```

**Comment by RX14** [comment]
@meew0 because you don't get their position in the string. We could build your method based on `parse_mensions(str, &block)`

**Comment by greenbigfrog** [comment]
#64 was reverted. Should this be reopened?
