### ISSUE TITLE
Does this work? What version of crystal is required?

### ISSUE THREAD

**Issue by g33kidd** [meew0/discordcr#55]
I'm having some troubles getting this lib to work correctly. Firstly it's telling me that `MemoryIO` is not supported, so I went in and changed it to `IO::Memory` since it was changed `MemoryIO -> IO::Memory`. Though, I still seem to be getting some errors from the JSON PullParser, telling me that `json.null` is not a method for `IO::Memory`.

Still very new to Crystal, so I'm not entirely sure what's going on. Would love some help, or info as to what I should do.

**Comment by greenbigfrog** [comment]
There's a channel on the Discord API server designated for questions like this: https://discord.gg/discord-api
Without looking too deep into your issue I'd guess that you are on a outdated version of crystal (or discordcr). I'd try updating both to latest

**Comment by RX14** [comment]
The `master` branch is compatible with latest crystal but the latest release is not. Please specify the master branch until the next release like so:
```cr
dependencies:
  discordcr:
    github: meew0/discordcr
    branch: master
```
