### ISSUE TITLE
Use a logger instead of puts

### ISSUE THREAD

**Issue by meew0** [meew0/discordcr#6]

**Comment by RX14** [comment]
Make sure to log raw message data from Gateway and REST to make generating error logs easier.

**Comment by RX14** [comment]
I think maybe we should be a little more verbose on debug. For example, we don't log REST requests, and logging of gateway messages is very inconsistent. I would like us to be able to reconstruct *exactly* what's happening on gateway and REST from a debug log.

**Comment by ColinRioux** [comment]
That's true, it would be more helpful. 

However, that being said, this section from client.cr

    rescue ex : JSON::ParseException
          LOGGER.error <<-LOG
            An exception occurred during message parsing! Please report this.
            #{ex}
            (pertaining to previous exception) Raised with packet:
            #{message}
            LOG
        rescue ex
          LOGGER.error <<-LOG
            A miscellaneous exception occurred during message handling.
            #{ex}
            LOG
        end
    end

When logged using the logger or the many puts statements, can be extremely long for long servers (one being Discord Bots). It's not really an issue, but it would be nice to limit the log to the best that we can.

**Comment by RX14** [comment]
@ColinRioux if those errors are being gnerated there's either a bug in your code or a bug in discordcr and they should be reported. That's why it doesn't matter that they're long. They should be log so you notice them and report them... like it asks you.

Have you reported them?

**Comment by meew0** [comment]
Closing this for now as the logger is implemented; please make further issues if there are still problems

**Comment by RX14** [comment]
See https://github.com/meew0/discordcr/issues/6#issuecomment-254006774 for why this was left open

**Comment by meew0** [comment]
Yes, but that is not what this issue is about ("Use a logger instead of puts"). Further logging advances could be in their own issue

**Comment by RX14** [comment]
ok
