### ISSUE TITLE
Inquiry: Add Ctx as dependency, or stdlib

### ISSUE THREAD

**Issue by z64** [meew0/discordcr#65]
Ctx is a small library I put together for my own needs, and thinking about it I think it may fit to has it as a standard library feature, or a dependency that can be optionally `require`'d.

https://github.com/z64/ctx

There are closed issues rejecting a command framework: This isn't one. This is something that can be used to build a "command bot", but ultimately, any serious bot will need this kind of functionality to *conditionally run event handlers based on lazily evaluated properties*. 

In my opinion this is still "lowest common denominator" of any kind of command framework that could be built on top of discordcr, and what initially made me (and others I've talked to) hesitant to start using it - I didn't want to use messy `case` paths, or `break`/`next` out of the blocks on conditionals in a non-DRY way, or not having those conditions able to change lazily, especially since Crystal is compiled.

Here's a snippet of usage from the README:
```crystal
# Instance a context to use with arbitrary MESSAGE_CREATE events
owner   = Ctx::Context.message_create { |m| m.author.id == 120571255635181568 }
content = Ctx::Context.message_create { |m| m.content.includes? "new fone" }

# Create the handler that matches both contexts
client.message_create(owner, content) do |payload|
  client.create_message(payload.channel_id, "who dis?")
end
```
Note that I do [define a #command method](https://github.com/z64/ctx/blob/master/src/ctx/bot.cr#L31-L44), as it allowed for the fastest creation of the most simple kind of context parsing, and again suited my own needs. I'm fine with removing it, or making any other adjustments as needed.

I do plan on porting more things to Crystal on top of discordcr. At the least, I would like to open a wiki page where community made components / frameworks, or even example bots can be found.

**Comment by z64** [comment]
My old `ctx` lib is wholly surpassed by https://github.com/z64/discordcr-middleware now, and definitely feels right as a separate shard. Offers a bunch of higher level functionality so I encourage others looking for an easier transition from `discordrb` or similar to take a look :+1:

**Comment by RX14** [comment]
Well, should we implement middlware in discordcr then?

**Comment by z64** [comment]
I'm not sure. With the goal of this library being a pure low level toolkit with as few opinionated abstractions as possible, I think it's kind of a grey area utility and keeping it separate is an easier answer. It feels more like a tiny framework, I guess. 

I wouldn't be opposed to it if @meew0 agrees. I think it significantly lowers the barrier of entry as I previously mentioned for those porting from other langs.

**Comment by RX14** [comment]
Middleware doesn't make a framework.
