### ISSUE TITLE
[Mac OS] Unexpected end of http request (Exception)

### ISSUE THREAD

**Issue by Kakise** [meew0/discordcr#70]
Hello, I have the following error: Unexpected end of http request (Exception) while using your library. 
I tried the examples but I also have this error. I'm using latest "master" version of discorde and crystal 0.22.0 installed with brew.

```Unexpected end of http request (Exception)
0x1091b0bf5: *CallStack::unwind:Array(Pointer(Void)) at ??
0x1091b0b91: *CallStack#initialize:Array(Pointer(Void)) at ??
0x1091b0b68: *CallStack::new:CallStack at ??
0x109194cc1: *raise<Exception>:NoReturn at ??
0x109194ca1: *raise<String>:NoReturn at ??
0x1092c0c5f: *HTTP::Client::Response::from_io<(OpenSSL::SSL::Socket::Client | TCPSocket), Bool, Bool>:HTTP::Client::Response at ??
0x1092c0c09: *HTTP::Client::Response::from_io<(OpenSSL::SSL::Socket::Client | TCPSocket)>:HTTP::Client::Response at ??
0x109274c31: *HTTP::WebSocket::Protocol::new<String, String, Int32, Bool>:HTTP::WebSocket::Protocol at ??
0x1092cdbbe: *HTTP::WebSocket::new<String, String, Int32, Bool>:HTTP::WebSocket at ??
0x109295f2f: *Discord::Client#initialize_websocket:HTTP::WebSocket at ??
0x109295e5f: *Discord::Client#initialize:token:client_id<String, UInt64>:Float64 at ??
0x109295d9c: *Discord::Client::new:token:client_id<String, UInt64>:Discord::Client at ??
0x109194788: __crystal_main at ??
0x1091a6288: main at ??
```

**Comment by z64** [comment]
This is a bug in Crystal 0.22.0

Please find your crystal stdlib (run `which crystal` for example) and insert this line:
https://github.com/RX14/crystal/blob/01c30000bcdc8ac54760495929b9d44f4eb37c33/src/http/web_socket/protocol.cr#L272

Recompile and you should be good to go.

**Comment by RX14** [comment]
This is actually https://github.com/crystal-lang/crystal/issues/4340 which I closed in https://github.com/crystal-lang/crystal/pull/4386. Unfortunately this patch hasn't made it to a crystal release yet. 

The fix I have been recommending to other people is to manually apply that [1-line fix](https://github.com/crystal-lang/crystal/pull/4386/files#diff-c30599f135415930b128db8e9064bbe2R272) to the stdlib. You can find the stdlib in `/opt/crystal` or `/usr/lib/crystal` on linux or `/usr/local/Cellar/crystal-lang/` if you're using homebrew.

**Comment by arubinofaux** [comment]
Yup @RX14 fix works perfectly

**Comment by Kakise** [comment]
The fix works perfectly

**Comment by RX14** [comment]
I'll keep this open until a new crystal version is released.

**Comment by z64** [comment]
With 0.23 released which covers https://github.com/crystal-lang/crystal/pull/4386, I believe we can close this now?
