### ISSUE TITLE
Voice heartbeat fiber not stopped after closing connection

### ISSUE THREAD

**Issue by snapcase** [meew0/discordcr#93]
Disconnecting from voice by sending a status update and closing the socket:
```cr
client.voice_state_update(guild, nil, false, false)
voice_client.close
```
results in the following traceback:
```
Unhandled exception in spawn:
Closed socket (IO::Error)
0x4e6e6b: *CallStack::unwind:Array(Pointer(Void)) at ??
0x647d30: check_open at /usr/lib/crystal/http/web_socket.cr 61:5
0x647cd8: send at /usr/lib/crystal/http/web_socket.cr 64:5
0x646de5: send at /home/snapcase/devel/crystal/wat/lib/discordcr/src/discordcr/websocket.cr 35:5
0x6a2c72: heartbeat_loop at /home/snapcase/devel/crystal/wat/lib/discordcr/src/discordcr/voice.cr 102:11
0x4e2f49: ??? at /usr/lib/crystal/kernel.cr 0:3
0x503e2e: run at /usr/lib/crystal/fiber.cr 255:3
0x4d49f6: ~proc2Proc(Fiber, (IO::FileDescriptor | Nil)) at /usr/lib/crystal/concurrent.cr 0:3
0x0: ??? at ??
```
which seems to be [Discord::VoiceClient#heartbeat_loop](https://github.com/meew0/discordcr/blob/master/src/discordcr/voice.cr#L99-L108) trying to keep the connection alive after disconnecting.

**Comment by RX14** [comment]
Yeah we recently reworked heartbeats in a branch and it waiting for @meew0 to merge: https://github.com/meew0/discordcr/pull/75/files

Hou should check out that branch and it should fix it.

**Comment by z64** [comment]
@RX14 This is for the voice websocket, not the regular gateway. It has its own heartbeat fiber that that PR doesn't modify.

**Comment by RX14** [comment]
Oh, oops
